put in explicit check for log writability

diff --git a/sbin/sync-cvmfs-fermilab b/sbin/sync-cvmfs-fermilab
--- a/sbin/sync-cvmfs-fermilab
+++ b/sbin/sync-cvmfs-fermilab
@@ -5,7 +5,15 @@
 TOP=/grid/fermiapp/cvmfsfermilab
 PROJTOP=$TOP/publish
 
-exec 3>&2 >>$TOP/logs/sync-cvmfs-fermilab.log 2>&1
+LOG=$TOP/logs/sync-cvmfs-fermilab.log
+if [ ! -w $LOG.new ]; then
+    # Need this separate check because bash does not complain when
+    #  '>>' is done onto a read-only filesystem.  Also test -w has to
+    #  be on a new file, otherwise it sees the file as writable.
+    echo "Cannot write to $LOG" >&2
+    exit 1
+fi
+exec 3>&2 >>$LOG 2>&1
 
 # if project name includes "products/" sync only that subdirectory,
 #   and if it doesn't, sync both top level and in products
